"""Add is_predefined flag to Recipe model

Revision ID: 95a31e3741ba
Revises: e02a62f8f37a
Create Date: 2024-12-03 19:42:43.345016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a31e3741ba'
down_revision = 'e02a62f8f37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_predefined', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_predefined')

    # ### end Alembic commands ###
