"""Add dietary and difficulty columns to Recipe model

Revision ID: c22542bd0528
Revises: 
Create Date: 2024-12-03 13:49:04.298972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22542bd0528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dietary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('dietary')

    # ### end Alembic commands ###
